# orgchart-mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: orgchart-mysql
spec:
  selector:
    app: orgchart-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP