# orgchart-secrets.yaml (Remember to encrypt this in production!)
apiVersion: v1
kind: Secret
metadata:
  name: orgchart-secrets
type: Opaque
data:
  db_host: bXlzcWw=  # mysql (base64 encoded)
  db_port: MzMwNg==  # 3306 (base64 encoded)
  db_database: b3JnY2hhcnRzCg==  # orgcharts (base64 encoded)
  db_username: b3JnY2hhcnRzX3VzZXIK  # orgcharts_user (base64 encoded)
  db_password: cGFzc3dvcmQ=  # password (base64 encoded)
  db_root_password: cm9vdHBhc3N3b3Jk  # rootpassword (base64 encoded)